### ISSUE TITLE
Design survey closure workflow

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#11]
**User Story:**
As a developer, I want a clear vision of the steps a user will take when closing and analyzing the results of a survey, so that I will have strong guidance for my implementation.

**Description:**
The wiki article [_Conceptual Lifecycle of a Survey_](https://help.github.com/en/github/authenticating-to-github/signing-commits) along with #4 lay the groundwork for this workflow. Now we need to envision the detailed subprocesses that make up survey closure.

**Acceptance Criteria:**
- [ ] Documentation (a write-up and/ or a diagram) of the flow
  - Identify the domain events that can trigger this workflow
  - Identify the input data needed
  - Identify the outputs
  - Identify decision points and feedback loops

**Comment by alexandratsitsiringos** [comment]
This post is in the process of being re-edited and changed/adjusted.

**Domain Model (Stage 3)**

Question Aggregate
- Question (Aggregate Root)
- QuestionType (Child Entity)
- DraftSurvey (Value Object)
- PublishedSurvey (Value Object)
- SharingOption (Child Entity) 

Answer Aggregate

- Answer/Responder (Aggregate Root)
- AnswerType (Child Entity)
- ReportType (Child Entity)
- CompletedSurvey (Value Object)
- ResponsesCollected (Value Object)
- AllResponsesCollected (Value Object)

Domain Events:
- CreateSurvey
- PublishSurvey
- CollectResponses
- ResponsesCompleted
- CloseSurvey
- Re-OpenSurvey
BeyondMVP: 
- DuplicateSurvey

**Input Types**
- verification of survey closure 
Beyond MVP Input Types: 
- help creator by providing a check on how many submissions have been completed to better decide if closure is appropriate: for example, distributed survey through email to 5 individuals, only 4 responded - survey closure not appropriate now 

**Output Types**
- completed report (available for download) 
- archived/inactive survey present in user account
- if responders visit the closed survey, they view a message explaining the closure - they are not given the option to submit anything 

Beyond MVP Output Types:
- completed report of additional data analysis options 
- completed "official report" 
- reports not only available for viewing or download, but also for social media distribution


**Decision Points**
- Survey Responses Incomplete 
- Survey Responses Complete 
- Survey Closes 

**Feedback Loops**
Input might need to be re-used to produce new output in the following cases/triggered by the following domain events:
- SurveyReOpened 
BeyondMVP: 
- Duplicate Survey as Clean Slate -> returns to survey creation workflow without the responses

**Comment by wbadart** [comment]
I especially like the decision points in this one; like what should we do if the owner tries to close a survey but someone has a response (draft) in progress? Like #10 I think we can work to pare down the scope and simplify some too.
