### ISSUE TITLE
Answer format support

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#7]
**User Story:**
As a user, I want a variety of possible answer formats to get a more accurate understanding of my survey takers' views.

**Description:**
The theme of this epic is support for different types of answers. For example, short-answer, paragraph/ long answer, one of many options, many of many options, etc. A good variety of possible formats should lead to richer survey result datasets.

**Linked User Stories:**

- TODO

**Acceptance Criteria:**
- [ ] Document an initial set of desired answer formats

**Comment by alexandratsitsiringos** [comment]
I think that if I had to choose the most critically needed answer formats, I would pick the following:
- required vs optional answers
- multiple choice answers (accepting one or multiple choices) 
- short vs long answers (text input) 

Further to consider for initial development:
- rate from 1 to 10
- checkbox
- dropdown
- multiple choice grid 
- checkbox grid

**Comment by wbadart** [comment]
I like where this is going. Let's try and decouple the semantics of an answer format (e.g. "select zero or more of many") from its presentation (e.g. "checkbox"). I think that leaves us with the following:

- Free response (i.e. unrestricted text entry)
  - Consider constraints on long answer vs. constraints on short answer
- Selection
  - Select one of many options
  - Select several of many options (min. number of selections?)
- Ranking/ rating/ sorting (can this be modeled via selection?)

Extra considerations:
- How to model (or render) selection with many options? E.g. country selection
- What constraints would be appropriate on the domain types of each of the above?

I'm curious, what specifically did you have in mind with the grid ideas?
