### ISSUE TITLE
Design survey deployment workflow

### ISSUE THREAD

**Issue by wbadart** [wbadart/coolsnappy#9]
**User Story:**
As a developer, I want a clear vision of the steps a user will take when deploying a survey, so that I will have strong guidance for my implementation.

**Description:**
The wiki article [_Conceptual Lifecycle of a Survey_](https://help.github.com/en/github/authenticating-to-github/signing-commits) along with #4 lay the groundwork for this workflow. Now we need to envision the detailed subprocesses that make up survey deployment and sharing.

**Acceptance Criteria:**
- [ ] Documentation (a write-up and/ or a diagram) of the flow
  - Identify the domain events that can trigger this workflow
  - Identify the input data needed
  - Identify the outputs
  - Identify decision points and feedback loops

**Comment by alexandratsitsiringos** [comment]
This post is in the process of being re-edited and changed/adjusted.

**Survey Deployment Domain Events**

Question Aggregate
Question (Aggregate Root)
QuestionType(Child Entity)
DraftSurvey(Value Object)
PublishedSurvey(Value Object)
SharingOption(ValueObject) 

Answer Aggregate
Answer/Responder (Aggregate Root)
ReportType(ChildEntity)
AnswerType(ValueObject)

Domain Events:
CreateSurvey
Publish Survey

**Input Types**
- verification of choice to publish 
- choice of sharing option: email or link
- choice of answer option: anonymous or including names

**Beyond MVP Input**
choice of sharing option: social media options 


**Output Types**
- Draft Version of Questions Created
_view questions as your responder would view them_
- Summary Report
_list of responses for short answer type question, pie chart or bar chart for multiple choice_
- Excel/CSV Compilation of Data

**Beyond MVP Output**
- Individual Report
_list responses based on individual_
- Question-Based Report
_list responses based on question_
- Official Report
_professionally-looking PDF file with all the answers collected based on the creator's choice of presentation responses_ 

**Decision Points**
Draft Survey Verified: Produce Published Survey 
Survey Publication Option Chosen 
Survey Responders are specific (based on email or username)
Survey Responders are anonymous
Answers required of survey taker
Answers are not required of survey taker

**Feedback Loops**
Input might need to be re-used to produce new output in the following cases/triggered by the following domain events:
- SurveyReOpened 
- ReportTypeChanged
 Beyond MVP: 
- ResponderRequestsEdits
- CreatorRequestsEdits (after publication)

**Comment by wbadart** [comment]
Very strong writeup. I'd add that in between "clicking publish" and "knowing List of emails the survey was distributed to" we should design one (or more) packaging formats. When I "click publish" what happens? We probably want to render the survey to HTML and get it to the user (survey owner). Maybe it downloads a zip with all the generated HTML to their machine? I'm thinking something like that so that we don't have to get into hosting/ distribution territory yet.

**Comment by wbadart** [comment]
Eventually, features like "generate shareable link" will be great to have, but that requires coolsnappy having some control of the backend; out of scope for the initial core library. In the meantime, that makes "deployment" just a matter of display. We can include a component that, for example, renders a Survey entity to html, but that won't involve designing a whole deployment workflow.
